server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: road3144

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 468836433955-mmavsqmklo29i4633qlvsjjc4s1ed0e0.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 2260816854081073
            client-secret: da0385a4883aaf125b224c77d4b6927f
            scope:
              - email
              - public_profile
          naver:
            client-id: rjFq489SbwmWV6Qfsfmp
            client-secret: bxovvD6_In
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # ?? ??? json?? ??? response?? ???? ???? ??

app:
  auth:
    tokenSecret: wdw_server_jjang
    tokenExpirationMsec: 864000000
#    (1000) * (60) * (60) * (24) * (365)